/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databasecon;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author 002rishav
 */
public class p3 extends javax.swing.JFrame {

    /**
     * Creates new form p3
     */
    public p3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton2.setText("POLICY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("AADHAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("VEHICLE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("POLICY_HOLDER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("PREMIUM");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("LATE_FINE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("View Table Details ");

        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("BILL");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8)
                                .addGap(31, 31, 31)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButton2)
                                .addGap(68, 68, 68)
                                .addComponent(jButton3)
                                .addGap(52, 52, 52)
                                .addComponent(jButton4)))
                        .addGap(47, 47, 47)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButton6)
                        .addGap(71, 71, 71)
                        .addComponent(jButton7)
                        .addGap(58, 58, 58)
                        .addComponent(jButton9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton8))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Queueoptions obj=new Queueoptions();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("oracle.jdbc.OracleDriver");
            Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","System","ronak");
            Statement stmt=con1.createStatement();
            ResultSet rs=stmt.executeQuery("select * from policy");
            String show="";
            show="POLICY_NUMBER\t"+"EFFECTIVE_DATE\t"+"EXPIRY_DATE\n";
            while(rs.next())
            {
                int apt_no=rs.getInt("POLICY_NUMBER");
                String type=rs.getString("EFFECTIVE_DATE");
                String bid=rs.getString("EXPIRY_DATE");
                show+=apt_no+"\t\t"+type+"\t"+bid+"\n";
             jTextArea2.setText(show);
            }
             rs.close();
             stmt.close();
             con1.close();
            }catch(Exception e) {JOptionPane.showMessageDialog(null,"Error="+e);} 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{Class.forName("oracle.jdbc.OracleDriver");
            Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","System","ronak");
            Statement stmt=con1.createStatement();
            ResultSet rs=stmt.executeQuery("select * from aadhar");
            String show="";
            show="AID\t"+"NAME\t"+"DOB\t\t"+"ADDRESS\n";
            while(rs.next())
            {
                int aid=rs.getInt("AID");
                String nm=rs.getString("NAME");
                String dat=rs.getString("DOB");
                String add=rs.getString("ADDRESS");
                show+=aid+"\t"+nm+"\t"+dat+"\t"+add+"\n";
             jTextArea2.setText(show);
            }
             rs.close();
             stmt.close();
             con1.close();
            }catch(Exception e) {JOptionPane.showMessageDialog(null,"Error="+e);}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{Class.forName("oracle.jdbc.OracleDriver");
            Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","System","ronak");
            Statement stmt=con1.createStatement();
            ResultSet rs=stmt.executeQuery("select * from vehicle");
            String show="";
            show="VEHICLE_NUMBER\t"+"CHASIS_NUMBER\t"+"COLOUR\t"+"MODEL\t"+"YEAR_BOUGHT\t"+"AID_OF_OWNER\n";
            while(rs.next())
            {
                String vno=rs.getString("VEHICLE_NUMBER");
                 String cno=rs.getString("CHASIS_NUMBER");
                  String clr=rs.getString("COLOUR");
                String mdl=rs.getString("MODEL");
                int yrb=rs.getInt("YEAR_BOUGHT"); 
                int aid=rs.getInt("AID_OF_OWNER");
                show+=vno+"\t\t"+cno+"\t\t"+clr+"\t"+mdl+"\t"+yrb+"\t\t"+aid+"\n";
             jTextArea2.setText(show);
            }
             rs.close();
             stmt.close();
             con1.close();
            }catch(Exception e) {JOptionPane.showMessageDialog(null,"Error="+e);}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{Class.forName("oracle.jdbc.OracleDriver");
            Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","System","ronak");
            Statement stmt=con1.createStatement();
            ResultSet rs=stmt.executeQuery("select * from policy_holder");
            String show="";
            show="POLICY_NO\t"+"NAME\t"+"LICENSE_NUMBER\t"+"AADHAR_ID\t"+"CITY\n";
            while(rs.next())
            {
                int pno=rs.getInt("POLICY_NO");
                String nm=rs.getString("NAME");
                String lno=rs.getString("LICENSE_NUMBER");
                int aid=rs.getInt("AADHAR_ID");
                String ct=rs.getString("CITY");
                show+=pno+"\t"+nm+"\t"+lno+"\t\t"+aid+"\t"+ct+"\n";
             jTextArea2.setText(show);
            }
             rs.close();
             stmt.close();
             con1.close();
            }catch(Exception e) {JOptionPane.showMessageDialog(null,"Error="+e);}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{Class.forName("oracle.jdbc.OracleDriver");
            Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","System","ronak");
            Statement stmt=con1.createStatement();
            ResultSet rs=stmt.executeQuery("select * from premium");
            String show="";
            show="POLICY_NUM\t"+"PREMIUM\t\t"+"DATE_PAID\t\t"+"NEXT_DUE_DATE\n";
            while(rs.next())
            {
                int pnum=rs.getInt("POLICY_NUM");
                int prm=rs.getInt("PREMIUM");
                String dp=rs.getString("DATE_PAID");
               String ndd=rs.getString("NEXT_DUE_DATE");
                show+=pnum+"\t"+prm+"\t\t"+dp+"\t"+ndd+"\n";
             jTextArea2.setText(show);
            }
             rs.close();
             stmt.close();
             con1.close();
            }catch(Exception e) {JOptionPane.showMessageDialog(null,"Error="+e);}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{Class.forName("oracle.jdbc.OracleDriver");
            Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","System","ronak");
            Statement stmt=con1.createStatement();
            ResultSet rs=stmt.executeQuery("select * from late_fine");
            String show="";
            show="MONTH_LATE\t"+"FINE\n";
            while(rs.next())
            {
                int mtl=rs.getInt("MONTH_LATE");
                int fin=rs.getInt("FINE");
                show+=mtl+"\t"+fin+"\n";
             jTextArea2.setText(show);
            }
             rs.close();
             stmt.close();
             con1.close();
            }catch(Exception e) {JOptionPane.showMessageDialog(null,"Error="+e);}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTextArea2.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       try{Class.forName("oracle.jdbc.OracleDriver");
            Connection con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","System","ronak");
            Statement stmt=con1.createStatement();
            ResultSet rs=stmt.executeQuery("select * from bill");
            String show="";
            show="POLICY_NO\t"+"PREMIUM\t"+"FINE\n";
            while(rs.next())
            {
                int pno=rs.getInt("POLICY_NO");
                int prm=rs.getInt("PREMIUM");
                int fin=rs.getInt("FINE");
                show+=pno+"\t"+prm+"\t"+fin+"\n";
             jTextArea2.setText(show);
            }
             rs.close();
             stmt.close();
             con1.close();
            }catch(Exception e) {JOptionPane.showMessageDialog(null,"Error="+e);}
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
